name: Build and Deploy to ECR

on:
  push:
    branches:
      - develop

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Validação de commits
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  Optional, for private repositories.
          allowed-commit-types: "feat,fix,chore" # Optional, set if you want a subset of commit types to be allowed.
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/app/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Maven Java App
        run: ./app/mvnw clean package -f ./app/pom.xml
      - name: Open PR
        id: check-open-prs
        uses: actions/github-script@v6
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                const { data: pullRequests } = await github.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                base: 'develop'
                });
                core.setOutput('open_prs', pullRequests.length > 0);
      
    #   - name: Upload JAR
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: app-jar
    #       path: target/demo.jar