name: Build and Deploy to ECR

on:
  push:
    branches:
      - feature/**

jobs:
  build-app:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
      - name: Validação de commits
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Optional, for private repositories.
          allowed-commit-types: "feat,fix,chore" # Optional, set if you want a subset of commit types to be allowed.
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '17'
      #     distribution: 'adopt'
      # - name: Cache Maven packages
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/app/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-m2
      # - name: Build with Maven
      #   run: ./app/mvnw -B package -f ./app/pom.xml
      # - name: Run unit tests
      #   run: ./app/mvnw test -f ./app/pom.xml