# TODO - Transformar em módulo para ser reutilizado
name: Build and Deploy to ECR




on:
  push:
    branches:
      - main

      
jobs:
  build-app:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  
    - name: Chafy Studio - App Java Maven
      id: app
      uses: ./.github/workflows/maven
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        codecov_token: ${{ secrets.CODECOV_TOKEN }}
    - name: Chafy Studio - Publish
      id: publish
      uses: ./.github/workflows/publish-image
      with:
        app_name: 'demo'
        app_version: ${{ steps.app.outputs.version }}
    - name: Listagem de arquivos
      shell: bash
      run: |
        ls /tmp -la